apiVersion: v1
kind: ServiceAccount
metadata:
  name: tasky-admin-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tasky-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: tasky-admin-sa
  namespace: default
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasky
  template:
    metadata:
      labels:
        app: tasky
    spec:
      serviceAccountName: tasky-admin-sa
      containers:
      - name: tasky
        image: wizregistry29260.azurecr.io/tasky:v1 
        ports:
        - containerPort: 8080
        env:
      
        - name: MONGODB_URI
          value: "mongodb://admin:WizExercise2026%21@20.217.202.223:27017/tasky?authSource=admin"
        - name: SECRET_KEY
          value: "secret123"
---
apiVersion: v1
kind: Service
metadata:
  name: tasky-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: tasky

